# Generated by Django 4.2.7 on 2023-11-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('group_quantity', models.IntegerField()),
                ('keyword_quantity', models.IntegerField()),
                ('old_messages_offset', models.IntegerField()),
                ('daemon_hours_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=80)),
                ('telegram_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expire_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='core.tariffplan')),
            ],
        ),
        migrations.CreateModel(
            name='SearchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_process', 'В процессе'), ('error', 'Ошибка'), ('finished', 'Завершен')], max_length=50)),
                ('table_link', models.CharField(max_length=1000)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'SearchList',
                'verbose_name_plural': 'SearchLists',
            },
        ),
    ]
