# Generated by Django 4.2.7 on 2023-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_telegramuser_tariff_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_accepted_rules',
            field=models.BooleanField(default=False),
        ),
    ]
