# Generated by Django 4.2.7 on 2023-11-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_expire_at_telegramuser_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initial', 'В сбооре'), ('ready', 'Ожидает поиска'), ('in_process', 'В процессе'), ('error', 'Ошибка'), ('finished', 'Завершен')], max_length=50)),
                ('table_link', models.CharField(max_length=1000)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
            },
        ),
        migrations.DeleteModel(
            name='SearchList',
        ),
    ]
