# Generated by Django 4.2.7 on 2023-12-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_search_created_at_alter_search_searched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
