# Generated by Django 4.2.7 on 2023-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tariffplan_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffplan',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
