# Generated by Django 4.2.7 on 2023-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='allowed_searches',
            field=models.IntegerField(null=True),
        ),
    ]
