# Generated by Django 4.2.7 on 2023-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_search_id_alter_tariffplan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='entity_chat_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='entity_message_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='entity_search_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='groups',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='search',
            name='keywords',
            field=models.JSONField(default={}),
        ),
    ]
