# Generated by Django 4.2.7 on 2023-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_search_entity_chat_id_search_entity_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='groups',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='keywords',
            field=models.JSONField(),
        ),
    ]
