# Generated by Django 4.2.7 on 2023-12-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_search_groups_alter_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='tariff_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_tariff', to='core.tariffplan'),
        ),
    ]
