# Generated by Django 4.2.7 on 2023-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_search_tariff_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='groups',
            new_name='searchable',
        ),
        migrations.AddField(
            model_name='search',
            name='search_type',
            field=models.CharField(default='telegram_chats', max_length=50),
        ),
    ]
