# Generated by Django 4.2.7 on 2023-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_groups_search_searchable_search_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched_at',
            field=models.DateTimeField(null=True),
        ),
    ]
