# Generated by Django 4.2.7 on 2023-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_search_searched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=50, null=True, unique=True)),
                ('api_id', models.CharField(max_length=255, null=True)),
                ('api_hash', models.CharField(max_length=255, null=True)),
                ('bot_token', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('password', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscribers', models.ManyToManyField(to='core.searchtelegramuser')),
            ],
            options={
                'ordering': ['telegram_id'],
            },
        ),
        migrations.CreateModel(
            name='SearchLead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('keywords', models.JSONField()),
                ('chats', models.ManyToManyField(null=True, to='core.telegramchat')),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='leads',
            field=models.ManyToManyField(to='core.searchlead'),
        ),
    ]
