# Generated by Django 4.2.7 on 2023-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_searchtelegramuser_telegramchat_searchlead_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchtelegramuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='searchtelegramuser',
            name='api_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchtelegramuser',
            name='api_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchtelegramuser',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchtelegramuser',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='searchtelegramuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
