# Generated by Django 4.2.7 on 2023-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_phone_number_searchtelegramuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='entity_search_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='leads',
            field=models.ManyToManyField(blank=True, to='core.searchlead'),
        ),
        migrations.AlterField(
            model_name='search',
            name='table_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
