# Generated by Django 4.2.5 on 2024-03-23 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_telegramuser_search_accounts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="is_accepted_rules",
            new_name="is_admin",
        ),
    ]
