# Generated by Django 4.2.5 on 2024-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_rename_is_accepted_rules_telegramuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_can_review",
            field=models.BooleanField(default=False),
        ),
    ]
