# Generated by Django 4.2.5 on 2024-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_telegramuser_is_can_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="is_can_review",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="role",
            field=models.CharField(blank=True, default="user", max_length=50),
        ),
    ]
