# Generated by Django 4.2.5 on 2024-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_telegramuser_is_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iin_or_bin",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "firstanme",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "lastname",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "text",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
        ),
    ]
