# Generated by Django 4.2.5 on 2024-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_debtor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtor",
            name="text",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
