# Generated by Django 4.2.5 on 2024-03-25 05:57

import app.apps.core.bot.enum
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_debtor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtor",
            name="status",
            field=models.CharField(
                default=app.apps.core.bot.enum.ReviewStatus["REQUESTED"], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="firstanme",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="iin_or_bin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="lastname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
