# Generated by Django 4.2.5 on 2024-03-25 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_debtor_status_alter_debtor_firstanme_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="debtor",
            old_name="firstanme",
            new_name="firstname",
        ),
    ]
